repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        language: system
        entry: cargo fmt
        pass_filenames: false
        types: [rust]
      - id: cargo-clippy
        name: cargo clippy
        language: system
        entry: cargo clippy
        pass_filenames: false
        types: [rust]
