[package]
name = "performance_send"
version = "0.1.0"
edition = "2024"

[dependencies]
rustecal = { path = "../../../rustecal", features = ["pubsub"] }
rustecal-pubsub = { path = "../../../rustecal-pubsub" }
rustecal-types-bytes = { path = "../../../rustecal-types-bytes" }
