[package]
name = "performance_send"
version = "0.1.0"
edition = "2021"

[dependencies]
rustecal = { path = "../../../rustecal", features = ["pubsub"] }
rustecal-core = { path = "../../../rustecal-core" }
rustecal-pubsub = { path = "../../../rustecal-pubsub" }
