[package]
name = "rustecal-pubsub"
version = "0.1.0"
edition = "2021"

[dependencies]
rustecal-sys  = { version = "0.1.0", path = "../rustecal-sys" }
rustecal-core = { version = "0.1.0", path = "../rustecal-core" }
thiserror     = "1.0"

[features]
default       = []
