[package]
name = "hello_send"
version = "0.1.0"
edition = "2024"

[dependencies]
rustecal = { path = "../../../rustecal", features = ["pubsub"] }
rustecal-types-string = { path = "../../../rustecal-types-string" }
